[project]
name = "yt-summary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "langdetect>=1.0.9",
    "openai>=1.67.0",
    "ruff>=0.11.0",
    "textblob>=0.19.0",
    "youtube-transcript-api>=1.0.3",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ERA001", "G004", "PIE808", "PD901", "T201", "TD002", "TD003", "S311"]